### ISSUE TITLE
run immediately on startup before cron scheduled time

### ISSUE THREAD

**Issue by xlv** [dschanoeh/hover-ddns#12]
I installed the package and the service on Fedora and AlmaLinux 8/9 with no problem and it's updating the IP every 15 minutes based on the cron schedule in the config file but I think it would be nice if it also ran when starting. For instance. I got a new IP address when rebooting my router but the update wasn't picked up right away when I booted my machine.

**Comment by xlv** [comment]
To try to explain it better:

Scheduler is set for every 15 minutes

10:16 I boot my router and get a new IP from my ISP
10:17 I boot my computer and the ddns service start
10:30 the IP address is updated on hover.com

I'd like the option to have the service perform an update at 1017 in the timeline above and check/update at 10:30 and every 15 minutes later on.

**Comment by dschanoeh** [comment]
Thanks for opening this issue. Indeed, that's a valid scenario that I hadn't considered. In my setup, getting a new address isn't tied to a reboot. I've created a snapshot build with the requested change. Could you please test it on your machine as well? Afterwards, I'll do a proper release. Thanks!

[hover-ddns_v0.5.2-next_Linux_arm64.tar.gz](https://github.com/dschanoeh/hover-ddns/files/8888443/hover-ddns_v0.5.2-next_Linux_arm64.tar.gz)
[hover-ddns_v0.5.2-next_Linux_armv6.tar.gz](https://github.com/dschanoeh/hover-ddns/files/8888448/hover-ddns_v0.5.2-next_Linux_armv6.tar.gz)
[hover-ddns_v0.5.2-next_Linux_armv7.tar.gz](https://github.com/dschanoeh/hover-ddns/files/8888450/hover-ddns_v0.5.2-next_Linux_armv7.tar.gz)
[hover-ddns_v0.5.2-next_Linux_mipsle_softfloat.tar.gz](https://github.com/dschanoeh/hover-ddns/files/8888452/hover-ddns_v0.5.2-next_Linux_mipsle_softfloat.tar.gz)
[hover-ddns_v0.5.2-next_Linux_x86_64.tar.gz](https://github.com/dschanoeh/hover-ddns/files/8888455/hover-ddns_v0.5.2-next_Linux_x86_64.tar.gz)

**Comment by xlv** [comment]
I've tested the x86_64 version and it works as expected.

Note that when you modify the documentation, you should mention that this also works for the initial startup when the hostname does not exist on hover.com.

Talking of documentation, the short description on github.com should use 'unofficial' instead of 'inofficial' as even if it's valid, it's rarely used. I noticed that the source code itself uses 'unofficial'. In fact I would change the description to "A Dynamic DNS client for Hover using their unofficial API"

**Comment by dschanoeh** [comment]
Fixed with release 0.6.0
