### ISSUE TITLE
ExecStart didn't match where it was installed via .deb.

### ISSUE THREAD

**Issue by abersnaze** [dschanoeh/hover-ddns#14]
I used the deb install option on ubuntu but the the systemd service didn't match where executable ended up.
```
$ uname -a
Linux ******* 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I made this change to the service file
```
$ diff hover-ddns.service hover-ddns.service_bkup 
8c8
< ExecStart=/usr/bin/hover-ddns --config /etc/hover-ddns.yaml
---
> ExecStart=/usr/local/bin/hover-ddns --config /etc/hover-ddns.yaml
```

Once I made that change worked great. Thanks for making this.

**Comment by dschanoeh** [comment]
Thanks for reporting! v0.6.1 should fix the issue and also moves the service file to the correct location. Could you please give this a try and confirm if it works in your environment as well? Thanks!
