### ISSUE TITLE
Does this support updating multiple domains and hosts?

### ISSUE THREAD

**Issue by ragesoss** [dschanoeh/hover-ddns#3]
This is great, exactly what I was looking for... and it's awesome that it's packaged for Debian. Thanks!

My two children each have a website, and both sites are hosted on the same Raspberry Pi. I'd like to be able to use this to updated a handful of records (the `@` and the `*` for each of two domains) on the same Hover account, to keep their websites up when our home IP changes. Is that possible?

**Comment by dschanoeh** [comment]
It doesn't support that yet but it certainly sounds like a useful feature. I'll add that when I have a bit of time.
In the meantime, you could try a (partial) workaround and simply run two instances in parallel by:
* Creating two config files (one for each domain)
* Duplicating the systemd service files under /etc/systemd/system and call them e.g. hover-ddns-domain1.service and hover-ddns-domain2.service and point each of them to one of the config files
* `systemctl daemon-reload`
* `systemctl enable hover-ddns-domain1.service`
* `systemctl start hover-ddns-domain1.service`
* `systemctl enable hover-ddns-domain2.service`
* `systemctl start hover-ddns-domain2.service`
... but that still doesn't allow you to change two host records but just one per domain.

**Comment by dschanoeh** [comment]
@ragesoss can you please give version 0.5.0 a try? It should do what you were asking for now.

**Comment by ragesoss** [comment]
I've updated to 0.5.1, and it's working! Thank you!
